# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Atracker' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Atracker
  pod 'RIBs', :git => 'https://github.com/uber/RIBs.git', :tag => '0.9.2'
  pod 'ReactorKit'
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'RxGesture'
  pod 'RxKeyboard'
  pod 'SnapKit'
  pod 'Then'
  pod 'Alamofire'
  pod 'GoogleSignIn'
  target 'AtrackerTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'AtrackerUITests' do
    # Pods for testing
  end

end
